name: Test Formalities

on:
  pull_request:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    name: Test Formalities
    uses: openwrt/actions-shared-workflows/.github/workflows/formal.yml@main
