
name: Build with tmate SSH Debug for XiaoMi-AX3600

on:
  workflow_dispatch:
    inputs:
      repo_choice:
        description: "Select source repo: openwrt, My_OpenWrt, immortalwrt, or lede"
        required: true
        default: "My_OpenWrt"
        type: choice
        options:
          - openwrt
          - My_OpenWrt
          - immortalwrt
          - lede
      manual_config:
        description: "Manually generate XiaoMi-AX3600 config via SSH (y/n)"
        default: "y"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3 rsync unzip zlib1g-dev file wget
        if apt-cache show python3-distutils 2>/dev/null | grep -q '^Version:'; then
          sudo apt-get install -y python3-distutils
        fi

    - name: Clone selected source code
      run: |
          case "${{ github.event.inputs.repo_choice }}" in
            openwrt)
              git clone https://github.com/openwrt/openwrt.git source
              ;;
            My_OpenWrt)
              git clone https://github.com/wong1975/My_OpenWrt.git source
              ;;
            immortalwrt)
              git clone https://github.com/immortalwrt/immortalwrt.git source
              ;;
            lede)
              git clone https://github.com/coolsnowwolf/lede.git source
              ;;
            *)
              echo "Invalid repository choice"
              exit 1
              ;;
          esac

    # SSH 远程调试（tmate），自动进入 make menuconfig
    - name: SSH 远程调试（tmate）进入 menuconfig
      if: ${{ github.event.inputs.manual_config == 'y' }}
      uses: mxschmitt/action-tmate@v3
      #with:
        #command: |
          #cd source
          #[ -f scripts/feeds ] && ./scripts/feeds update -a && ./scripts/feeds install -a
          #make menuconfig

    - name: Find and copy first .config (if any)
      run: |
          find . -name .config -print -exec cp {} ./found.config \; -quit
          ls -l found.config || echo "No .config found"

    - name: Upload .config from all possible locations
      uses: actions/upload-artifact@v4
      with:
          name: config
          path: |
            found.config
            source/.config
            .config
